name: CI/CD

on:
  push:
    branches:
    - develop

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@develop
    - uses: actions/setup-node@develop
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build:dev
    - uses: w9jds/firebase-action@develop
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
